INSERT INTO wms.mPeriod(iPeriod, dStart, dEnd, sStat) VALUES (201301, to_date('2013/01/01', 'yyyy/MM/dd'), to_date('2013/01/31', 'yyyy/MM/dd'), 'CLOSE');
INSERT INTO wms.mPeriod(iPeriod, dStart, dEnd, sStat) VALUES (201302, to_date('2013/02/01', 'yyyy/MM/dd'), to_date('2013/02/28', 'yyyy/MM/dd'), 'CLOSE');
INSERT INTO wms.mPeriod(iPeriod, dStart, dEnd, sStat) VALUES (201303, to_date('2013/03/01', 'yyyy/MM/dd'), to_date('2013/03/31', 'yyyy/MM/dd'), 'CLOSE');
INSERT INTO wms.mPeriod(iPeriod, dStart, dEnd, sStat) VALUES (201304, to_date('2013/04/01', 'yyyy/MM/dd'), to_date('2013/04/30', 'yyyy/MM/dd'), 'OPEN');

INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA01', 1, 'Incoming Pallet A01');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA02', 1, 'Incoming Pallet A02');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA03', 1, 'Incoming Pallet A03');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA04', 1, 'Incoming Pallet A04');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA05', 1, 'Incoming Pallet A05');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA06', 1, 'Incoming Pallet A06');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA07', 1, 'Incoming Pallet A07');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA08', 1, 'Incoming Pallet A08');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA09', 1, 'Incoming Pallet A09');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA10', 1, 'Incoming Pallet A10');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA11', 1, 'Incoming Pallet A11');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA12', 1, 'Incoming Pallet A12');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA13', 1, 'Incoming Pallet A13');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA14', 1, 'Incoming Pallet A14');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA15', 1, 'Incoming Pallet A15');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA16', 1, 'Incoming Pallet A16');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA17', 1, 'Incoming Pallet A17');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA18', 1, 'Incoming Pallet A18');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA19', 1, 'Incoming Pallet A19');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('IA20', 1, 'Incoming Pallet A20');

INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA01', 2, 'Delivery Pallet A01');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA02', 2, 'Delivery Pallet A02');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA03', 2, 'Delivery Pallet A03');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA04', 2, 'Delivery Pallet A04');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA05', 2, 'Delivery Pallet A05');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA06', 2, 'Delivery Pallet A06');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA07', 2, 'Delivery Pallet A07');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA08', 2, 'Delivery Pallet A08');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA09', 2, 'Delivery Pallet A09');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OA10', 2, 'Delivery Pallet A10');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB01', 2, 'Delivery Pallet B01');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB02', 2, 'Delivery Pallet B02');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB03', 2, 'Delivery Pallet B03');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB04', 2, 'Delivery Pallet B04');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB05', 2, 'Delivery Pallet B05');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB06', 2, 'Delivery Pallet B06');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB07', 2, 'Delivery Pallet B07');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB08', 2, 'Delivery Pallet B08');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB09', 2, 'Delivery Pallet B09');
INSERT INTO wms.mPallet(sPallet, iType, sDesc) VALUES('OB10', 2, 'Delivery Pallet B10');
